service: client
runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /
    static_files: dist/client-annidev/index.html
    upload: dist/client-annidev/index.html

  - url: /
    static_dir: dist/client-annidev
